name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pip install build
      - run: python -m build
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [3.8, 3.9, 3.10]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: pytest
    